# Workflow to build and deploy site to Vercel using Hugo

# Name of Workflow
name: deploy-production

# Controls when the action will run. Triggers the workflow on push
# events but only for the vercel branch
on:
  push:
    branches: [ vercel ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy-production"
  deploy-production:

    # The environment this job references
    environment:
      name: Production
      url: ${{ steps.vercel-action.outputs.preview-url }}

    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v2
      with:
          ssh-key: ${{ secrets.SUBMODULE_CONTENT_DEPLOY_KEY }}
          submodules: recursive  # Fetch private content

    # Step 2 - Install Hugo (specific version)
    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.83.0'

    # Step 3 - Install Package Dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4 - Builds the site using Hugo
    - name: Build
      run: hugo -v -e staging && npm run algolia
      env:
        ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
        ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        ALGOLIA_INDEX_FILE: ${{ secrets.ALGOLIA_INDEX_FILE }}
        ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}

    # Step 5 - Push our generated site to Vercel
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      id: vercel-action
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        #github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  #Required
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} #Required
        github-comment: false
        vercel-args: '--prod' #Optional
        working-directory: public
